[options]
db_host = localhost
db_name = db_maxmotor_uat
db_port = 5432
db_user = odoo
db_password = odoo
addons_path = odoo/addons,odoo/addons-mammut,odoo/addons-iran
without_demo = all
log_level = info
http_port = 9090
admin_passwd = $pbkdf2-sha512$600000$fM8Zg1Cq1brXutc6R0gp5Q$Rc/5dmR5MJVMLPkUX1MGbO2AVL34UejxqOwRi8WNNhU1XVv0UTtbLjxcoAAWsqW8y85pyOeNCrQTv3nXBM9nWA

