[options]
db_host = localhost
db_name = db_mammut_uat
db_port = 5432
db_user = odoo
db_password = odoo
addons_path = odoo/addons,odoo/addons-mammut,odoo/addons-iran
without_demo = all
log_level = info
http_port = 9090